title: Rabbits
author: Me
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  So you know that it is this thing that you already know so yeah its that thing we already know its like a thing we know but we knew it already like its just a thing you know.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
